---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./flux/non-prod
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  patches:
    - patch: |
        - op: add
          path: /spec/template/metadata/annotations/traffic.sidecar.istio.io~1excludeInboundPorts
          value: "8080"
      target:
        kind: Deployment
        labelSelector: "app.kubernetes.io/part-of=flux"
